spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  application:
    name: webstack-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: webstack-vue
    password: TiKEdcY88HWesTJ3
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  profiles:
    active: dev


server:
  port: 8081
  baseUrl: http://localhost:5173
logging:
  level:
    root: info